### ISSUE TITLE
Add instructions to enable multiple job users (or if it's impossible)

### ISSUE THREAD

**Issue by Denommus** [quag/user-nix-steam-deck#2]
For now, nix is using just one core when doing a heavy job, it would be nice to have multiple parallel jobs.

**Comment by quag** [comment]
Can you give me an example, so I can try to replicate?

Nix usually uses multiple cores. Could it be the specific package only builds with a single core?

**Comment by Denommus** [comment]
I figured out, you need to specify `max-jobs = auto` in nix.conf.

**Comment by quag** [comment]
Thanks! Do you think I should set that by default?

**Comment by Denommus** [comment]
I think it's a good default.

**Comment by quag** [comment]
I’m also thinking of adding auto-optimise-store = true as a default. Do you have any thoughts on that or other things that should be turned on?

**Comment by Denommus** [comment]
I think auto-optimise-store is better to be left to the user to decide. A generally good idea is to see what the default `nix.conf` in a default NixOS installation looks like.

**Comment by quag** [comment]
I've updated the nix.conf to default to having max-jobs = auto. Can you let me know if that works for you?

It seems like a reasonable default for the Steam Deck as it has plenty of cores. The risk is that some packages fail to build with more than one job. If I get reports of that I'll remove the setting to use all the cores.

**Comment by Denommus** [comment]
LGTM
